# Generated by Django 4.1.7 on 2023-05-24 21:01

from django.db import migrations, models
import django.db.models.deletion
import pharmacy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('medicine_image', models.ImageField(upload_to='img', verbose_name='Medicine Image')),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_description', models.TextField()),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pharmacy_id', models.CharField(default=True, max_length=255, verbose_name=pharmacy.models.Pharmacy)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255)),
                ('offer_image', models.ImageField(upload_to='img', verbose_name='Offer Image')),
                ('offer_description', models.TextField()),
                ('offer_previous_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('offer_new_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('pharmacy_image', models.ImageField(upload_to='img', verbose_name='Pharmacy Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('subscription_type', models.CharField(max_length=255, null=True)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(null=True)),
                ('Pharmacy1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacy')),
                ('Subscription1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.subscription')),
            ],
        ),
    ]
