# Generated by Django 4.1.7 on 2023-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('pharmacy_image', models.ImageField(null=True, upload_to='img', verbose_name='Pharmacy Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
