# Generated by Django 4.1.7 on 2023-05-24 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_pharmacy',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
