# Generated by Django 4.1.7 on 2023-05-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pharmacy_pharmacy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('medicine_image', models.ImageField(default=None, null=True, upload_to='img')),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_description', models.TextField()),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
