# Generated by Django 4.1.7 on 2023-05-25 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_medicine_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
