# Generated by Django 4.1.7 on 2023-05-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medicine_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255)),
                ('offer_image', models.ImageField(upload_to='img', verbose_name='Offer Image')),
                ('offer_description', models.TextField()),
                ('offer_previous_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('offer_new_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
