# Generated by Django 4.1.7 on 2023-05-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_pharmacy_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacy_medicine',
        ),
    ]
