# Generated by Django 4.1.7 on 2023-05-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacy_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='serial_number',
            field=models.CharField(max_length=255),
        ),
    ]
