# Generated by Django 4.1.7 on 2023-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_rename_pharmacy1_subscription_pharmacy_pharmacy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(max_length=255),
        ),
    ]
