# Generated by Django 4.1.7 on 2023-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy_medicine',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
